config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  root "events#index"

  resources :events do
    resources :comments, only: [:create, :destroy]
    resources :subscriptions, only: [:create, :destroy]
    resources :photos, only: [:create, :destroy]

    post :show, on: :member
  end

  resources :users, only: [:show, :edit, :update, :destroy]
end

app/models/user.rb
class User < ApplicationRecord
  before_validation :set_name, on: :create

  after_commit :link_subscriptions, on: :create

  mount_uploader :avatar, AvatarUploader

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :omniauthable, omniauth_providers: %i[facebook vkontakte]

  has_many :events
  has_many :comments, dependent: :destroy
  has_many :subscriptions

  validates :name, presence: true, length: {maximum: 35}

  def send_devise_notification(notification, *args)
    devise_mailer.send(notification, self, *args).deliver_later
  end

  def self.find_for_facebook_oauth(access_token)
    find_or_create_from_email_provider_url_name(
      email: access_token.info.email,
      provider: access_token.provider,
      url: "https://facebook.com/#{access_token.extra.raw_info.id}",
      name: access_token.info.name,
      remote_avatar_url: "#{access_token.info.image}?type=large"
    )
  end

  def self.find_for_vkontakte_oauth(access_token)
    find_or_create_from_email_provider_url_name(
      email: access_token.info.email,
      provider: access_token.provider,
      url: access_token.info.urls.Vkontakte,
      name: access_token.info.name,
    remote_avatar_url: access_token.extra.raw_info.photo_400_orig
    )
  end

  private

  def self.find_or_create_from_email_provider_url_name(email:, provider:, url:, remote_avatar_url:, name:)
    return nil if email.nil?

    user = find_by(email: email)
    return user if user.present?

    where(url: url, provider: provider).first_or_create! do |user|
      user.email = email
      user.password = Devise.friendly_token.first(16)
      user.name = name
      user.remote_avatar_url = remote_avatar_url
    end
  end

  def link_subscriptions
    Subscription.where(user_id: nil, user_email: email).update_all(user_id: id)
  end

  def set_name
    self.name = "Комрад №#{rand(999)}" if name.blank?
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    @user = User.find_for_facebook_oauth(request.env['omniauth.auth'])

    if @user.nil?
      flash[:alert] = I18n.t('devise.omniauth_callbacks.profile_without_email', kind: 'Facebook')
      redirect_to root_path
    elsif @user.persisted?
      flash[:notice] = I18n.t('devise.omniauth_callbacks.success', kind: 'Facebook')
      sign_in_and_redirect @user, event: :authentication
    else
      flash[:error] = I18n.t('devise.omniauth_callbacks.failure', kind: 'Facebook',)
      redirect_to root_path
    end
  end

  def vkontakte
    @user = User.find_for_vkontakte_oauth(request.env['omniauth.auth'])

    if @user.nil?
      flash[:alert] = I18n.t('devise.omniauth_callbacks.profile_without_email', kind: 'Вконтакте')
      redirect_to root_path
    elsif @user.persisted?
      flash[:notice] = I18n.t('devise.omniauth_callbacks.success', kind: 'ВКонтакте')
      sign_in_and_redirect @user, event: :authentication
    else
      flash[:error] = I18n.t('devise.omniauth_callbacks.failure', kind: 'Вконтакте',)
      redirect_to root_path
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, except: [:show]
  before_action :set_current_user, except: [:show]

  def show
    @user = User.find(params[:id])
  end

  def edit
  end

  def update
    if @user.update(user_params)
      redirect_to @user, notice: I18n.t('controllers.users.updated')
    else
      render :edit
    end
  end

  def destroy
    @user.destroy
    redirect_to root_url, notice: 'Пользователь удален'
  end

  private

  def set_current_user
    @user = current_user
  end

  def user_params
    params.require(:user).permit(:name, :email, :avatar)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= simple_form_for(@user, html: {multipart: true}, validate: true) do |f| %>
  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :email %>
    <%= f.text_field :email, class: 'form-control', require: true %>
  </div>

  <div class="form-group">
    <%= f.label :avatar %>
    <p class="file-field"><%= image_tag(@user.avatar.thumb.url) if @user.avatar? %></p>
    <%= f.file_field :avatar %>
  </div>

  <div class="actions">
    <%= f.submit 'Сохранить', class: 'btn btn-primary' %>
    или <%= link_to 'вернуться', :back %>

    <p>
      <%= link_to 'Сменить пароль', edit_user_registration_path %>
    </p>

    <%= link_to 'Удалить аккаунт', @user,
                :method => :delete,
                data: { confirm: t('destroy_confirm.user') },
                class: 'btn btn-danger mt-4' %>
    </div>
<% end %>

app/views/users/_user.html.erb
<span class="user">
  <span class="user-avatar">
    <%= image_tag(user_avatar(user), class: 'img-icon') %>
  </span>
  <span class="user-name">
    <% if request.path == user_path(user) %>
      <%= user.name %>
    <% else %>
      <%= link_to user.name, user_path(user) %>
    <% end %>
  </span>
</span>

app/views/users/edit.html.erb
<h1>Редактирование профиля</h1>

<div class="row">
  <div class="col-md-6">
    <%= render 'form' %>
  </div>
</div>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<div class="text-center">
  <h1><%= @user.name %></h1>

  <%= image_tag user_avatar(@user), class: 'avatar-rounded my-3' %>

  <% if @user == current_user %>
    <p>
      <%= link_to 'Редактировать профиль', edit_user_path(@user), class: 'btn btn-link' %>
    </p>
  <% end %>
</div>

<div class="row">
  <div class="col-md-12">
    <% if @user.events.any? %>
      <h3>Организовал:</h3>
      <div class="row">
        <%= render partial: 'events/event', collection: @user.events %>
      </div>
    <% else %>
      <p>Пользователь пока не организовал ни одного события</p>
    <% end %>
  </div>
</div>