config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  root "events#index"

  resources :events do
    resources :comments, only: [:create, :destroy]
    resources :subscriptions, only: [:create, :destroy]
    resources :photos, only: [:create, :destroy]

    post :show, on: :member
  end

  resources :users, only: [:show, :edit, :update, :destroy]
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :user

  has_many :comments, dependent: :destroy
  has_many :subscriptions
  has_many :subscribers, through: :subscriptions, source: :user
  has_many :photos, dependent: :delete_all

  validates :title, presence: true, length: {maximum: 255}
  validates :address, presence: true
  validates :datetime, presence: true

  def visitors
    (subscribers + [user]).uniq
  end

  def pincode_valid?(pin2check)
    pincode == pin2check
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :authenticate_user!, except: [:show, :index]
  before_action :set_event, except: [:index, :new, :create]
  before_action :password_guard!, only: [:show]
  after_action :verify_authorized, except: [:index]

  def index
    @events = policy_scope(Event)
  end

  def show
    @new_comment = @event.comments.build(params[:comment])
    @new_subscription = @event.subscriptions.build(params[:subscription])
    @new_photo = @event.photos.build(params[:photo])

    authorize @event
  end

  def new
    @event = current_user.events.build

    authorize @event
  end

  def edit
    authorize @event
  end

  def create
    @event = current_user.events.build(event_params)

    authorize @event

    if @event.save
      redirect_to @event, notice: I18n.t('controllers.events.created')
    else
      render :new
    end
  end

  def update
    authorize @event

    if @event.update(event_params)
      redirect_to @event, notice: I18n.t('controllers.events.updated')
    else
      render :edit
    end
  end

  def destroy
    authorize @event

    @event.destroy
    redirect_to events_url, notice: I18n.t('controllers.events.destroyed')
  end

  private

  def password_guard!
    return true if @event.pincode.blank?
    return true if signed_in? && current_user == @event.user

    if params[:pincode].present? && @event.pincode_valid?(params[:pincode])
      cookies.permanent["events_#{@event.id}_pincode"] = params[:pincode]
    end

    unless @event.pincode_valid?(cookies.permanent["events_#{@event.id}_pincode"])
      flash.now[:alert] = I18n.t('controllers.events.wrong_pincode') if params[:pincode].present?
      render 'password_form'
    end
  end

  def set_event
    @event = Event.find(params[:id])
  end

  def event_params
    params.require(:event).permit(:title, :address, :datetime, :description, :pincode)
  end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_event.html.erb
<div class="col-sm-6 col-md-4 my-3">
  <div class="thumbnail">
    <%= content_tag 'div', '', class: 'event-background',
                    style: "background-image: url(#{asset_path('event_thumb.jpg')})" %>

    <div class="thumbnail-inner event-info-inner">
      <div class="caption">
        <div class="event-description">
          <h3><%= link_to event.title, event_path(event) %></h3>
          <h3>
            <small><%= l event.datetime, format: :short %></small>
          </h3>
          <div><%= event.address %></div>
        </div>

        <div class="event-visitors">
          <% event.visitors.each do |user| %>
            <%= image_tag user_avatar_thumb(user), class: 'img-icon mt-2', title: user.name %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/events/_form.html.erb
<%= simple_form_for @event, validate: true do |f| %>
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :address %>
    <%= f.text_field :address, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :datetime %>
    <p><%= f.datetime_select :datetime, class: 'form-control' %></p>
  </div>

  <div class="form-group">
    <%= f.label :description %>
    <%= f.text_area :description, class: 'form-control resize-vertical' %>
  </div>

  <div class="form-group">
    <%= f.label :pincode %>
    <%= f.text_field :pincode, class: 'form-control' %>
  </div>

  <div class="actions">
    <%= f.submit 'Сохранить', class: 'btn btn-primary' %>
    или <%= link_to 'вернуться', :back %>
  </div>

  <%= link_to 'Удалить событие', @event,
              :method => :delete,
              data: { confirm: t('destroy_confirm.event') },
              class: 'btn btn-danger mt-5' %>
<% end %>

app/views/events/edit.html.erb
<h1>Редактирование события</h1>

<div class="row">
  <div class="col-md-6">
    <%= render 'form' %>
  </div>
</div>

app/views/events/index.html.erb
<h1>События</h1>

<div class="my-3">
  <%= link_to 'Создать событие', new_event_path, class: 'btn btn-success' %>
</div>

<div class="row">
  <%= render partial: 'events/event', collection: @events %>
</div>

app/views/events/new.html.erb
<h1>Новое событие</h1>

<div class="row">
  <div class="col-md-6">
    <%= render 'form' %>
  </div>
</div>

app/views/events/password_form.html.erb
<h1>Доступ только по пин-коду</h1>

<div class="row">
  <div class="col-md-4">
    <%= form_tag('', method: 'post') do %>
      <div class="form-group">
        <%= label 'Пин-код', :pincode %>
        <%= text_field_tag :pincode, params[:pincode], class: 'form-control' %>
      </div>

      <div class="actions">
        <%= submit_tag 'Отправить', class: 'btn btn-primary' %>
      </div>
    <% end %>

    <%= link_to 'На главную', events_path %>
  </div>
</div>

app/views/events/show.html.erb
<div class="event">
  <div class="event-info row">
    <div class="col-md-12">
      <%= content_tag 'div', '', class: 'event-background',
                      style: "background-image: url(#{event_photo(@event)})" %>

      <div class="event-info-inner row">
        <div class="col-md-6 pt-3">
          <div class="event-description">
            <h1><%= @event.title %></h1>
            <h3><%= l @event.datetime, format: :short %></h3>
            <p><%= @event.description %></p>
            <p><%= @event.address %></p>
          </div>

          <% if current_user_can_edit?(@event) %>
            <div>
              <%= link_to 'Изменить', edit_event_path(@event), class: 'btn btn-primary' %>
            </div>
          <% end %>
        </div>

        <div class="col-md-6 py-3">
          <div id="map"
               data-address="<%= @event.address %>"
               style="width: 100%; height: 400px;">
          </div>
        </div>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col-md-8">
      <div class="event-photos pb-3 border-bottom">
        <% unless @event.photos.except(@new_photo).blank? %>
            <div class="event-photos-gallery pb-3">
              <%= render partial: 'photos/photo', collection: @event.photos.except(@new_photo) %>
            </div>
        <% end %>

        <% if policy(Event).create? %>
          <div class="event-photo-form pb-3">
            <%= render partial: 'photos/form', locals: {photo: @new_photo || @event.photos.build} %>
          </div>
        <% end %>
      </div>

      <div class="event-comments">
        <% unless @event.comments.except(@new_comment).blank? %>
          <div>
            <button class="btn btn-link pl-0" data-toggle="collapse" href="#collapseComments" role="button">
              Скрыть комментарии
            </button>


            <div class="collapse show pb-3" id="collapseComments">
              <%= render partial: 'comments/comment',
                         collection: @event.comments.except(@new_comment) %>
            </div>
          </div>
        <% end %>

        <div class="pb-3 border-bottom">
          <%= render partial: 'comments/form',
                     locals: {comment: @new_comment || @event.comments.build} %>

        </div>
      </div>
    </div>

    <div class="col-md-4">
      <div class="pb-3 border-bottom">
        <div class="event-owner">
          <h4>Зовет:</h4>
          <p><%= render partial: 'users/user', object: @event.user %></p>
        </div>
        <div class="event-subscriptions">
          <h4>Пойдут:</h4>
          <div>
            <p>
              <%= render partial: 'subscriptions/subscription',
                         collection: @event.subscriptions.except(@new_subscription) %>
            </p>
          </div>
        </div>
        <% if @event.user != current_user %>
          <div class="event-subscription-form">
            <h4>Я пойду:</h4>
            <div>
              <%= render partial: 'subscriptions/form', locals: {
                  subscription: @new_subscription || @event.subscriptions.build
              } %>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>